demo1: AreaOfRegion.cpp
	g++ AreaOfRegion.cpp -lsfml-graphics -lsfml-window -lsfml-system -o demo1

demo2: AreaOfRegion.cpp
	g++ AreaOfRegion_CHECKPOINTING_ENABLED.cpp -lsfml-graphics -lsfml-window -lsfml-system -o demo2
